---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: bookworm64
    box: debian/bookworm64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 9001, host: 9001"
  - name: bullseye64
    box: debian/bullseye64
provisioner:
  name: ansible
  become: true
lint: |
  set -e
  yamllint .
  ansible-lint
